Start implementing include modified /IM switch
tjscience/RoboSharp pull request #198
Opened 2024-03-10 20:01 UTC by PCAssistSoftware

Start implementing include modified /IM switch

2024-03-10 20:13 UTC, PCAssistSoftware commented
@RFBomb - have started making changes to implement include modified /IM switch as per request in #197

Would appreciate your input and checking of this to make sure I have a) done it correctly and b) also not sure what changes (if any) may be needed in relation to below:

ProgressEstimator.cs   - not sure if we need to handle tweaked in any special way like you do IncludeTweaked around line 453 approx.

RoboSharpConfiguration.cs  line 278 approx. (and related code in ProcessedFileFlags.cs) – do we need to do similar handling re LogParsing for include modified?

2024-03-11 20:03 UTC, RFBomb requested changes

2024-03-11 20:03 UTC, RFBomb commented on RoboSharp/SelectionFlags.cs
> +        IncludeModified = 1024,
This potentially breaks previous jobs!
- If any consumers were using `OnlyCopyArchiveFiles` or `OnlyCopyArchiveFilesAndResetArchiveFlag`, and happened to be also using serialization, that would get serialized to the 1024 value. Upon updating the library, it would read in IncludeModified instead of `OnlyCopyArchiveFiles`.
- Any new values should be appended to the end of the enum. (Location of the value in the list doesn't matter, but the assigned value does)

Recomendation: 
IncludeModified = 4096
OnlyCopyArchiveFiles = 1024
OnlyCopyArchiveFilesAndResetArchiveFlag = 2048

2024-03-11 20:04 UTC, RFBomb commented
From the docs (posting for reference) 

> <html><body>
<!--StartFragment-->
/im | Include modified files (differing change times).
-- | --
/is | Includes the same files. Same files are identical in name, size, times, and all attributes.
/it | Includes "tweaked" files. Tweaked files have the same name, size, and times, but different attributes.

<!--EndFragment-->
</body>
</html>

> Modified files classification applies only when both source and destination filesystems support change timestamps, such as NTFS, and the source and destination files have different change times but are otherwise the same. These files aren't copied by default. Specify /IM to include them.

---
Most of your changes look good, except on the enumeration of SelectionFlags

Ill take a peak at PE and Configuration momentarily

2024-03-11 20:10 UTC, PCAssistSoftware commented
Have resolved the SelectionFlags enumeration - wrongly assumed they should be in order - thank you for advising

2024-03-11 20:12 UTC, RFBomb commented
I believe that both Configuration and ProgressEstimator will have to be modified accordingly: 

For configuration, I think we will likely need something for it:
( Note that i'm assuming the default for en-us is `modified`, but only running the command and seeing the inclusion in the log can verify this )

```
/// <summary>
/// Log Lines starting with this string indicate : File was included by <see cref="SelectionOptions.IncludeModified"/> filters
/// </summary>
public string LogParsing_ModifiedInclusion
{
    get { return modifiedIncludedToken ?? GetDefaultConfiguration().modifiedIncludedToken ?? "modified"; }
    set { modifiedIncludedToken= value; }
}
private string modifiedIncludedToken;
```

ProgressEstimator : 
```
case true when currentFile.FileClass.Equals(Config.LogParsing_ModifiedInclusion, StringComparison.CurrentCultureIgnoreCase):  //IncludeModified
                            SkippedOrCopied(currentFile, !Command.SelectionOptions.IncludeModified);
                            break;
```

I also believe that once this is put in, Extensions should add support for it. But I can figure that out as part of my draft PR.

2024-03-11 20:14 UTC, PCAssistSoftware commented
> Note that i'm assuming the default for en-us is `modified`, but only running the command and seeing the inclusion in the log can verify this 

That is a correct assumption looking at my test logs

2024-03-11 20:18 UTC, PCAssistSoftware commented
@RFBomb - thanks for that, have made suggested changes, please double check I have located them in correct place etc.

2024-03-11 20:20 UTC, RFBomb commented
All looks good to me.

2024-03-11 20:23 UTC, PCAssistSoftware commented
> > Note that i'm assuming the default for en-us is `modified`, but only running the command and seeing the inclusion in the log can verify this
> 
> That is a correct assumption looking at my test logs

@RFBomb 

Correction, I was incorrect, it actually appears in log with a capital M as per below - is it case sensitive in the code? do I need to change line 292 of RoboSharpConfiguration from "modified" to "Modified" ?


-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : 10 March 2024 19:25:24
   Source : C:\Users\darre\OneDrive\Desktop\source\
     Dest : C:\Users\darre\OneDrive\Desktop\destination\

    Files : *.*

  Options : *.* /L /DCOPY:DA /COPY:DAT /IM /R:1000000 /W:30

------------------------------------------------------------------------------

                           1    C:\Users\darre\OneDrive\Desktop\source\
            Modified               1.0 m        v750.pdf

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :         1         0         1         0         0         0
   Files :         1         1         0         0         0         0
   Bytes :    1.04 m    1.04 m         0         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00
   Ended : 10 March 2024 19:25:24

2024-03-11 21:30 UTC, PCAssistSoftware commented
If you can confirm a) whether I need to change it to a capital M as above, and b) that you are happy with this - then I will get this one merged in for now at least

2024-03-11 21:55 UTC, RFBomb commented
The case does not matter as we are looking at the comparison using IgnoreCase.

I'm vaguely recalling that the Upper/Lower in the log itself indicates why robocopy did with the file. Upper is include, lower is skip. Maybe vice versa. But we are handling that based on the parameters we know we passed into the command.

2024-03-11 22:02 UTC, PCAssistSoftware commented
idiot (me not you) - I should have checked the code and realized we were using CurrentCultureIgnoreCase - sorry been a long day, not thinking fully, apologies.

Yes that is correct, just found my notes on it, uppercase means copied, lowercase means skipped for the following:

Newer / newer
Older / older
Changed / changed
Tweaked / tweaked
Same / same

Are you happy for me to merge this then?

2024-03-11 22:03 UTC, RFBomb commented
Yep look good

2024-03-11 22:04 UTC, merged

2024-03-12 17:27 UTC, PCAssistSoftware commented
@RFBomb 

Quick question.

Should we have also included "LogParsing_ModifiedInclusion" in the following locations:

ProcessedFileFlags.cs > public enum ProcessedFileFlag

and

RoboSharpConfiguration.cs > public static string GetFileClass

2024-03-12 17:30 UTC, RFBomb commented
Yea, good catch.

2024-03-12 17:34 UTC, PCAssistSoftware commented
> Yea, good catch.

will get it done shortly then